// Public endpoint for the personal Android home-screen widget.
// Returns only the fields needed to render Dad's "확인필요" list.
const DATABASE_ID = process.env.NOTION_DATABASE_ID || "8ba2d174-b03c-8369-b0a2-07b234b93430";
async function notionQuery(token,start_cursor){const body={page_size:100};if(start_cursor)body.start_cursor=start_cursor;const r=await fetch(`https://api.notion.com/v1/databases/${DATABASE_ID}/query`,{method:"POST",headers:{Authorization:`Bearer ${token}`,"Notion-Version":"2022-06-28","Content-Type":"application/json"},body:JSON.stringify(body)});if(!r.ok){const text=await r.text();throw new Error(`Notion ${r.status}: ${text.slice(0,300)}`);}return r.json();}
function text(prop){if(!prop)return "";if(prop.type==="title")return(prop.title||[]).map(x=>x.plain_text||"").join("");if(prop.type==="rich_text")return(prop.rich_text||[]).map(x=>x.plain_text||"").join("");if(prop.type==="select")return prop.select?.name||"";if(prop.type==="status")return prop.status?.name||"";return "";}
function projectName(raw){const rawText=String(raw||"").trim();if(!rawText)return "기타";const key=rawText.toLowerCase().replace(/\s+/g,"").replace(/_/g,"-");const map={"clean-member":"클린멤버","cleanmember":"클린멤버","클린멤버":"클린멤버","clean-manager":"클린매니저","cleanmanager":"클린매니저","클린매니저":"클린매니저","cleanery":"크리너리","크리너리":"크리너리","kbo":"KBO","kbo-toto":"KBO","kbo-toto-auto":"KBO","master-project":"마스터 프로젝트","masterproject":"마스터 프로젝트","마스터프로젝트":"마스터 프로젝트","dain-event":"다인이벤트","dainevent":"다인이벤트","dine-event":"다인이벤트","dineevent":"다인이벤트","다인이벤트":"다인이벤트","ai업무시스템":"AI 업무 시스템","ai-work-system":"AI 업무 시스템","aiworksystem":"AI 업무 시스템","기타":"기타"};return map[key]||"기타";}
const projectOrder=["클린멤버","클린매니저","크리너리","KBO","마스터 프로젝트","다인이벤트","AI 업무 시스템","기타"];
export default async function handler(req,res){if(req.method!=="GET")return res.status(405).json({ok:false,error:"Method not allowed"});const token=process.env.NOTION_TOKEN;if(!token)return res.status(503).json({ok:false,error:"NOTION_TOKEN is not configured"});try{let cursor,unfinished=0;const items=[];do{const data=await notionQuery(token,cursor);for(const page of data.results||[]){const p=page.properties||{};const status=text(p["상태"]);if(status!=="완료")unfinished++;const checked=p["확인필요"]?.type==="checkbox"&&p["확인필요"].checkbox;if(checked)items.push({id:page.id,title:text(p["작업명"])||"(제목 없음)",project:projectName(text(p["프로젝트명"])),status});}cursor=data.has_more?data.next_cursor:undefined;}while(cursor);
items.sort((a,b)=>{const pa=projectOrder.indexOf(a.project),pb=projectOrder.indexOf(b.project);const ai=pa<0?999:pa,bi=pb<0?999:pb;if(ai!==bi)return ai-bi;const ad=a.status==="완료"?1:0,bd=b.status==="완료"?1:0;if(ad!==bd)return ad-bd;return String(a.title||"").localeCompare(String(b.title||""),"ko");});
res.setHeader("Cache-Control","public, s-maxage=60, stale-while-revalidate=120");return res.status(200).json({ok:true,needsCheck:items.length,unfinished,items});}catch(e){console.error(e);return res.status(500).json({ok:false,error:"summary unavailable"});}}
